### ISSUE TITLE
Create super-simple design system components lib

### ISSUE THREAD

**Issue by with-heart** [iotv/web#6]
This can live in `web` for now, but I think it makes sense to isolate our building block components and their styles like your `Button` component and other shit so we can save ourselves from having to find and modify `className` all over the place down the road.

**Comment by DavidJFelix** [comment]
I was going to keep building blocks in `/components` and nothing else but reusable items. For other stuff I was gonna put in a structure *similar* (but not identical) to their paths in the router. I don't want to nest everything in components if I can and would prefer a flatter tree where it makes sense.
